// ============================================================
// CORE Iris — ブランド案件マーケットプレイス (シードデータ)
// 実物品質のオファー: 実在/実在しそうな企業名 + 具体的な報酬・締切・応募窓口。
// プレースホルダー禁止。各カードは「今すぐ応募できる」体験を目指す。
// ============================================================
import type { Platform, ContentType } from '../types/influencerDeal';

export type BrandCategory =
  | 'beauty'
  | 'fashion'
  | 'health'
  | 'food'
  | 'lifestyle'
  | 'travel'
  | 'pet'
  | 'tech'
  | 'learning'
  | 'home';

export const CATEGORY_META: Record<BrandCategory, { label: string; emoji: string; color: string }> = {
  beauty:    { label: '美容・コスメ',     emoji: '💄', color: '#E1306C' },
  fashion:   { label: 'ファッション',     emoji: '👗', color: '#833AB4' },
  health:    { label: 'ヘルス・フィットネス', emoji: '🏃', color: '#10B981' },
  food:      { label: '食品・グルメ',     emoji: '🍱', color: '#F77737' },
  lifestyle: { label: 'ライフスタイル',   emoji: '✨', color: '#A78BFA' },
  travel:    { label: '旅行・体験',       emoji: '✈️', color: '#3B82F6' },
  pet:       { label: 'ペット',           emoji: '🐶', color: '#FFA94D' },
  tech:      { label: 'テック・ガジェット', emoji: '💻', color: '#64748B' },
  learning:  { label: '学び・キャリア',   emoji: '📚', color: '#0EA5E9' },
  home:      { label: 'ホーム・インテリア', emoji: '🪴', color: '#84CC16' },
};

export interface BrandDeal {
  id: string;
  brandName: string;
  productName: string;
  category: BrandCategory;
  summary: string;            // 案件の概要 (一行)
  description: string;        // 詳しい説明 (商品の魅力 + 期待する投稿の雰囲気)
  fee: number;                // 報酬 (円)
  feeNote?: string;           // 例: 「+ 商品 ¥8,800 相当を進呈」
  /** 最低フォロワー要件 */
  minFollowers: number;
  /** 推奨フォロワー上限 (ニッチ案件のミスマッチを避けるため。なければ Infinity 扱い) */
  maxFollowers?: number;
  /** 主要プラットフォーム */
  platform: Platform;
  /** 投稿形式 */
  contentType: ContentType;
  /** 締切 (YYYY-MM-DD) */
  deadline: string;
  /** 応募窓口 */
  contact:
    | { type: 'email'; address: string }
    | { type: 'form';  url: string };
  /** マッチを高めるための嗜好キーワード (オーディエンス層) */
  audienceTags: string[];
  /** どんな投稿になるか (例: 「自然光で商品を映す Reels」) */
  postExample?: string;
  /** PR表記の有無 (実案件で多いので明示) */
  prRequired: boolean;
  /** 投稿時の必須ハッシュタグ */
  requiredHashtags?: string[];
  /** 同時応募可能か */
  exclusive?: boolean;
  /** ブランド側の人物 (担当者) */
  contactPerson?: string;
}

// ------------------------------------------------------------
// シードデータ (100+ 件)
// ------------------------------------------------------------
//
// ※ 実在しそうな企業 + 公式風メアド / form URL。実際の応募先は
//   ユーザーが自分のリレーションで使う想定。Iris は「探索」と「下書き生成」
//   までを担い、最終送信は本人が判断する。
// ------------------------------------------------------------

const DEALS: BrandDeal[] = [
  // ─── 美容 / コスメ (24) ────────────────────────────────
  {
    id: 'b-001',
    brandName: '資生堂 (SHISEIDO)',
    productName: 'アルティミューン パワライジング コンセントレート N',
    category: 'beauty',
    summary: 'リール 1 本 + ストーリー 3 投稿',
    description: '朝のスキンケア時間を見せるリール。本品 (¥11,000) を 3 週間使った肌の変化レポを、自然光で。',
    fee: 80000,
    feeNote: '+ 本品 30ml 進呈 (¥11,000 相当)',
    minFollowers: 8000,
    maxFollowers: 80000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-06-30',
    contact: { type: 'email', address: 'creator-partners@shiseido.co.jp' },
    audienceTags: ['30代女性', 'スキンケア', '美容', '働く女性'],
    postExample: '朝のメイク前ルーティン (60 秒) — クレンジング後の素肌 → 美容液をひたひたに → 仕上がりのツヤ感',
    prRequired: true,
    requiredHashtags: ['#PR', '#アルティミューン', '#資生堂'],
    contactPerson: '広報部 影山様',
  },
  {
    id: 'b-002',
    brandName: 'コーセー (KOSÉ)',
    productName: '雪肌精 クリアウェルネス トリートメントローション',
    category: 'beauty',
    summary: 'フィード投稿 1 + ストーリー 2',
    description: '日本酒由来の発酵成分を含む化粧水。2 週間使った乾燥対策レポ。',
    fee: 50000,
    feeNote: '+ 商品 200ml 進呈 (¥3,850 相当)',
    minFollowers: 5000,
    maxFollowers: 50000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-07-15',
    contact: { type: 'email', address: 'pr.influencer@kose.co.jp' },
    audienceTags: ['20代女性', '30代女性', 'スキンケア', 'ナチュラル志向'],
    postExample: 'バスルームでの朝晩ルーティン写真 4 枚 + キャプションに「2 週間で変わったこと」',
    prRequired: true,
    requiredHashtags: ['#PR', '#雪肌精クリアウェルネス'],
  },
  {
    id: 'b-003',
    brandName: '花王 (Kao) ビオレ',
    productName: 'ビオレ UV アクアリッチ ライトアップエッセンス',
    category: 'beauty',
    summary: '夏のリール 1 本',
    description: '朝の日焼け止め習慣を 30 秒リールで。トーンアップ感を画面で見せられる構図に。',
    fee: 35000,
    minFollowers: 3000,
    maxFollowers: 30000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-06-20',
    contact: { type: 'email', address: 'biore-promotion@kao.co.jp' },
    audienceTags: ['10代', '20代女性', 'プチプラ', 'UV対策'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ビオレUV'],
  },
  {
    id: 'b-004',
    brandName: 'マンダム (mandom) ギャツビー',
    productName: 'GATSBY ヘアジャム — マッシュ用',
    category: 'beauty',
    summary: 'メンズ向けスタイリングリール',
    description: 'マッシュ・センターパートの 1 分セット動画。ビフォーアフター必須。',
    fee: 45000,
    minFollowers: 5000,
    platform: 'tiktok',
    contentType: 'short',
    deadline: '2026-07-05',
    contact: { type: 'email', address: 'gatsby-pr@mandom.co.jp' },
    audienceTags: ['10代男性', '20代男性', 'メンズ美容', '学生'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ギャツビー'],
  },
  {
    id: 'b-005',
    brandName: 'イプサ (IPSA)',
    productName: 'ザ・タイムR アクア',
    category: 'beauty',
    summary: '医薬部外品化粧水のサンプリング企画',
    description: '肌測定 (ME) 体験を絡めた 3 投稿シリーズ。店頭体験 → 商品レビュー → 1 ヶ月後の変化。',
    fee: 120000,
    feeNote: '+ 店頭カウンセリング招待 (1 万円相当)',
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-10',
    contact: { type: 'email', address: 'ipsa.brand@shiseido.co.jp' },
    audienceTags: ['30代女性', '40代女性', '美容', '都市部'],
    prRequired: true,
    requiredHashtags: ['#PR', '#IPSA', '#ザタイムRアクア'],
  },
  {
    id: 'b-006',
    brandName: 'ロクシタン (L\'OCCITANE) 日本',
    productName: 'シア ハンドクリーム — ローズ',
    category: 'beauty',
    summary: 'ホリデー限定パッケージのアンボックス + ギフトシーン',
    description: 'プレゼント包装で届く特別仕様。「受け取った瞬間」のリアクションを 30 秒リールで。',
    fee: 60000,
    feeNote: '+ ホリデーコフレ 1 セット (¥7,150 相当)',
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-11-15',
    contact: { type: 'form', url: 'https://jp.loccitane.com/creator-partner' },
    audienceTags: ['20代女性', '30代女性', 'ギフト', 'ライフスタイル'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ロクシタン', '#LOccitaneHoliday'],
  },
  {
    id: 'b-007',
    brandName: 'THE BODY SHOP 日本',
    productName: 'ブリティッシュローズ アイマスク',
    category: 'beauty',
    summary: 'おうち時間リラックスフィード',
    description: 'お風呂後のセルフケア風景。リラックスする香りの表現が鍵。',
    fee: 30000,
    feeNote: '+ 商品 3 点進呈',
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-07-25',
    contact: { type: 'email', address: 'pr.jp@thebodyshop.com' },
    audienceTags: ['20代女性', '30代女性', 'サステナブル', 'リラックス'],
    prRequired: true,
    requiredHashtags: ['#PR', '#TheBodyShopJapan'],
  },
  {
    id: 'b-008',
    brandName: 'ジョー マローン ロンドン',
    productName: 'イングリッシュ ペアー & フリージア コロン',
    category: 'beauty',
    summary: '香りを写真で伝える 1 投稿',
    description: '秋のフィードで「香りの記憶」を写真と言葉で。ボトルの撮り方ガイドライン有り。',
    fee: 90000,
    feeNote: '+ コロン 30ml 進呈 (¥14,300 相当)',
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'jomalone.jp@estee.com' },
    audienceTags: ['30代女性', '香水', '上質', '都市部'],
    prRequired: true,
    requiredHashtags: ['#PR', '#JoMaloneLondon'],
    exclusive: true,
  },
  {
    id: 'b-009',
    brandName: 'BOTANIST',
    productName: 'ボタニカルシャンプー&トリートメント (モイスト)',
    category: 'beauty',
    summary: 'バスルームショットのリール',
    description: '朝シャンの実写リール (60 秒)。香り・泡立ち・指通りを 3 ショットで。',
    fee: 40000,
    feeNote: '+ シャンプー+トリートメント セット',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-10',
    contact: { type: 'email', address: 'partner@botanistofficial.com' },
    audienceTags: ['20代女性', 'ヘアケア', 'ナチュラル'],
    prRequired: true,
    requiredHashtags: ['#PR', '#BOTANIST'],
  },
  {
    id: 'b-010',
    brandName: 'FUJIMI',
    productName: 'パーソナライズ サプリメント',
    category: 'beauty',
    summary: '美容診断 → 1 ヶ月レポ',
    description: 'オンライン診断 (体験会込) → 自分専用サプリの 1 ヶ月レポを 3 投稿でストーリーテリング。',
    fee: 70000,
    feeNote: '+ 1 ヶ月分サプリ (¥7,980 相当)',
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-07-31',
    contact: { type: 'form', url: 'https://fujimi.me/creator-program' },
    audienceTags: ['30代女性', '40代女性', 'インナーケア', '美容'],
    prRequired: true,
    requiredHashtags: ['#PR', '#FUJIMI'],
  },
  {
    id: 'b-011',
    brandName: 'オルビス (ORBIS) ユー',
    productName: 'ORBIS U エッセンスローション',
    category: 'beauty',
    summary: '化粧水の使用感を語るフィード',
    description: '30 代スキンケアの転換期に向けた化粧水。乾燥/ハリ実感のレポ + ボトル写真。',
    fee: 38000,
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-15',
    contact: { type: 'email', address: 'orbis-pr@orbis.co.jp' },
    audienceTags: ['30代女性', '働く女性', 'スキンケア'],
    prRequired: true,
    requiredHashtags: ['#PR', '#オルビスユー'],
  },
  {
    id: 'b-012',
    brandName: 'NULL',
    productName: 'NULL メンズ オールインワンジェル',
    category: 'beauty',
    summary: 'メンズスキンケア朝ルーティン',
    description: '洗顔 → ジェル 1 本仕上げの 30 秒動画。「忙しい朝に 30 秒」がコピー。',
    fee: 32000,
    minFollowers: 4000,
    platform: 'tiktok',
    contentType: 'short',
    deadline: '2026-07-15',
    contact: { type: 'email', address: 'null-pr@null-corp.jp' },
    audienceTags: ['20代男性', '30代男性', 'メンズ美容'],
    prRequired: true,
    requiredHashtags: ['#PR', '#NULLメンズ'],
  },
  {
    id: 'b-013',
    brandName: 'ZENB',
    productName: 'ZENB ヌードル — 黄えんどう豆 100%',
    category: 'beauty',
    summary: '美容×食のクロスオーバー',
    description: '糖質 30% オフ・植物性のヌードル。「美容のために食事を整える」文脈で 2 投稿。',
    fee: 55000,
    feeNote: '+ 24 食入りセット',
    minFollowers: 7000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-31',
    contact: { type: 'email', address: 'partner@zenb.jp' },
    audienceTags: ['30代女性', 'インナービューティー', 'ヘルシー'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ZENB'],
  },
  {
    id: 'b-014',
    brandName: 'SHIRO',
    productName: 'サボン ボディコロン',
    category: 'beauty',
    summary: 'ナチュラル香水の朝のひと振り',
    description: '朝のメイク後の「ひと振り」をリールで。30 秒。',
    fee: 48000,
    feeNote: '+ コロン 100ml (¥4,180 相当)',
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-15',
    contact: { type: 'email', address: 'pr@shiro-shiro.jp' },
    audienceTags: ['20代女性', '30代女性', '香水', 'ナチュラル'],
    prRequired: true,
    requiredHashtags: ['#PR', '#SHIRO'],
  },
  {
    id: 'b-015',
    brandName: 'Athletia (アスレティア)',
    productName: 'リフレッシング バスソルト',
    category: 'beauty',
    summary: 'バスタイムを丁寧に描く',
    description: 'スポーツ後 / 一日の終わりのバスタイム。柚子と海塩の香りを言葉で。',
    fee: 42000,
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-10',
    contact: { type: 'form', url: 'https://www.athletia-beauty.com/creator' },
    audienceTags: ['30代女性', 'フィットネス', 'ウェルネス'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Athletia'],
  },
  {
    id: 'b-016',
    brandName: 'Aēsop 日本',
    productName: 'レスレクション ハンドウォッシュ',
    category: 'beauty',
    summary: '手洗いを儀式に変える',
    description: '洗面所のディテール写真 + 「手を洗う」という動作を再定義する文章。',
    fee: 75000,
    minFollowers: 10000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-30',
    contact: { type: 'email', address: 'jp.creator@aesop.com' },
    audienceTags: ['30代', '40代', 'デザイン', '上質'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Aesop'],
    exclusive: true,
  },
  {
    id: 'b-017',
    brandName: 'CLINIQUE (クリニーク)',
    productName: 'ハッピー オードパルファム',
    category: 'beauty',
    summary: '夏の香水コラボ',
    description: '夏の朝の幸福感を香りで表現。リール 30 秒 + ストーリー 2 枚。',
    fee: 65000,
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-20',
    contact: { type: 'email', address: 'clinique.jp@estee.com' },
    audienceTags: ['20代女性', '30代女性', '香水'],
    prRequired: true,
    requiredHashtags: ['#PR', '#CliniqueHappy'],
  },
  {
    id: 'b-018',
    brandName: 'M·A·C コスメティックス',
    productName: 'リップスティック — Ruby Woo',
    category: 'beauty',
    summary: '赤リップで秋の 1 枚',
    description: 'マスクなしの「全顔メイク」フィード。リップを主役にした構図。',
    fee: 85000,
    feeNote: '+ リップスティック 3 本進呈',
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'mac.jp@estee.com' },
    audienceTags: ['20代女性', 'メイク', '個性派'],
    prRequired: true,
    requiredHashtags: ['#PR', '#MACRubyWoo'],
  },
  {
    id: 'b-019',
    brandName: 'メイクアップ フォーエバー',
    productName: 'HD スキン ファンデーション',
    category: 'beauty',
    summary: 'ベースメイクの密着レポ',
    description: '塗る前 → 8 時間後の比較を 60 秒動画で。',
    fee: 55000,
    minFollowers: 8000,
    platform: 'tiktok',
    contentType: 'short',
    deadline: '2026-08-25',
    contact: { type: 'email', address: 'mufe.jp@lvmh-pco.com' },
    audienceTags: ['20代女性', 'メイク', 'プロ志向'],
    prRequired: true,
    requiredHashtags: ['#PR', '#MUFE_HDSKIN'],
  },
  {
    id: 'b-020',
    brandName: 'KATE (カネボウ)',
    productName: 'リップモンスター — 蜃気楼',
    category: 'beauty',
    summary: 'マスクオフ時代のリップ',
    description: '飲み物を飲む → 落ちない検証。30 秒で。',
    fee: 30000,
    minFollowers: 3000,
    platform: 'tiktok',
    contentType: 'short',
    deadline: '2026-07-10',
    contact: { type: 'email', address: 'kate-pr@kanebo-cosmetics.co.jp' },
    audienceTags: ['10代', '20代女性', 'プチプラ'],
    prRequired: true,
    requiredHashtags: ['#PR', '#KATEリップモンスター'],
  },
  {
    id: 'b-021',
    brandName: 'CHANEL BEAUTY',
    productName: 'ルージュ ココ フラッシュ',
    category: 'beauty',
    summary: 'ラグジュアリーリップキャンペーン',
    description: '美しい光と影でリップを撮る。フィード+ストーリー 5 枚。',
    fee: 200000,
    feeNote: '+ リップ 2 本 (¥10,000 相当)',
    minFollowers: 30000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-30',
    contact: { type: 'email', address: 'beauty.jp@chanel.com' },
    audienceTags: ['30代女性', 'ラグジュアリー', 'メイク'],
    prRequired: true,
    requiredHashtags: ['#PR', '#CHANELBEAUTY'],
    exclusive: true,
  },
  {
    id: 'b-022',
    brandName: 'AHC (エーエイチシー)',
    productName: 'アイクリーム フォーフェイス',
    category: 'beauty',
    summary: '韓国コスメ朝ルーティン',
    description: '目元 → 顔全体に使える 1 本。1 分のリール。',
    fee: 28000,
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-20',
    contact: { type: 'email', address: 'ahc.jp@carverkorea.com' },
    audienceTags: ['20代女性', '韓国コスメ', 'スキンケア'],
    prRequired: true,
    requiredHashtags: ['#PR', '#AHC'],
  },
  {
    id: 'b-023',
    brandName: 'CICAPAIR (シカペア)',
    productName: 'リカバー クリーム',
    category: 'beauty',
    summary: '赤み肌のレスキューレポ',
    description: '寝不足や肌荒れに対する 3 日間レポ。ビフォーアフター必須。',
    fee: 38000,
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-10',
    contact: { type: 'email', address: 'cicapair.jp@drjart.com' },
    audienceTags: ['20代女性', '30代女性', 'スキンケア', '敏感肌'],
    prRequired: true,
    requiredHashtags: ['#PR', '#シカペア'],
  },
  {
    id: 'b-024',
    brandName: 'D-UP (ディーアップ)',
    productName: 'シルキーリキッドアイライナー',
    category: 'beauty',
    summary: 'アイラインの引き方ハウツー',
    description: '初心者向けの 60 秒チュートリアル。',
    fee: 22000,
    minFollowers: 3000,
    platform: 'tiktok',
    contentType: 'short',
    deadline: '2026-07-05',
    contact: { type: 'email', address: 'pr@d-up.co.jp' },
    audienceTags: ['10代', '20代女性', 'プチプラ', 'メイク初心者'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ディーアップ'],
  },

  // ─── ファッション (16) ──────────────────────────────────
  {
    id: 'f-001',
    brandName: 'ユニクロ (UNIQLO)',
    productName: 'エアリズム コットン T シャツ — 2026 SS',
    category: 'fashion',
    summary: '夏の 1 枚を着こなすコーデ',
    description: 'シンプル T を主役にした 3 コーデを 1 投稿に。',
    fee: 60000,
    feeNote: '+ 商品 5 点進呈',
    minFollowers: 10000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-06-25',
    contact: { type: 'email', address: 'lifewear-partners@uniqlo.com' },
    audienceTags: ['20代', '30代', 'シンプル', 'ベーシック'],
    prRequired: true,
    requiredHashtags: ['#PR', '#UNIQLO'],
  },
  {
    id: 'f-002',
    brandName: 'GU',
    productName: 'カットソー ワンピース',
    category: 'fashion',
    summary: 'プチプラワンピで春コーデ',
    description: '¥1,990 のワンピで作る 3 シーンコーデ。',
    fee: 35000,
    feeNote: '+ 商品 3 点進呈 (¥6,000 相当)',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-06-15',
    contact: { type: 'email', address: 'gu-influencer@gu-global.com' },
    audienceTags: ['10代', '20代女性', 'プチプラ', '学生'],
    prRequired: true,
    requiredHashtags: ['#PR', '#GU'],
  },
  {
    id: 'f-003',
    brandName: 'ZOZOTOWN',
    productName: 'ZOZOWEEK セール特集',
    category: 'fashion',
    summary: 'セール購入品の正直レビュー',
    description: '購入金額の 30% バック + 投稿料。自分で買って、リアル感のあるレビュー。',
    fee: 40000,
    feeNote: '+ 購入金額 30% バック (上限 ¥30,000)',
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-20',
    contact: { type: 'form', url: 'https://zozo.jp/biz/creators' },
    audienceTags: ['20代女性', 'お買い物', 'トレンド'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ZOZOWEEK'],
  },
  {
    id: 'f-004',
    brandName: 'GRL (グレイル)',
    productName: 'シアートップス + プリーツスカートセット',
    category: 'fashion',
    summary: 'デート服コーデ動画',
    description: '春夏のデート想定コーデ。リール 30 秒。',
    fee: 28000,
    feeNote: '+ 商品 2 着進呈',
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-06-30',
    contact: { type: 'email', address: 'pr@grail.bz' },
    audienceTags: ['10代', '20代女性', 'プチプラ', 'トレンド'],
    prRequired: true,
    requiredHashtags: ['#PR', '#GRL'],
  },
  {
    id: 'f-005',
    brandName: 'SNIDEL (スナイデル)',
    productName: 'フラワープリントワンピース 2026 SS',
    category: 'fashion',
    summary: 'フェミニンコーデ 2 投稿',
    description: 'ブランドの世界観 (シアー・フラワー) に合った撮影必須。',
    fee: 90000,
    feeNote: '+ ワンピース 1 着 (¥28,600 相当)',
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-07-10',
    contact: { type: 'email', address: 'snidel-pr@mash-group.jp' },
    audienceTags: ['20代女性', '30代女性', 'フェミニン'],
    prRequired: true,
    requiredHashtags: ['#PR', '#SNIDEL'],
    exclusive: true,
  },
  {
    id: 'f-006',
    brandName: 'Mila Owen (ミラオーウェン)',
    productName: 'リネンブレンドジャケット',
    category: 'fashion',
    summary: '通勤コーデの提案',
    description: '20 代後半〜30 代女性向け。オフィスとカジュアルの中間。',
    fee: 65000,
    feeNote: '+ ジャケット 1 着 (¥17,600 相当)',
    minFollowers: 10000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-20',
    contact: { type: 'email', address: 'milaowen-pr@mash-group.jp' },
    audienceTags: ['20代女性', '30代女性', '通勤', 'シンプル'],
    prRequired: true,
    requiredHashtags: ['#PR', '#MilaOwen'],
  },
  {
    id: 'f-007',
    brandName: 'BEAMS BOY',
    productName: 'バンドカラーシャツ',
    category: 'fashion',
    summary: 'ユニセックスコーデ',
    description: 'メンズ・ウィメンズの両軸で着こなす。',
    fee: 70000,
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-10',
    contact: { type: 'email', address: 'beamsboy-pr@beams.co.jp' },
    audienceTags: ['20代', '30代', 'ユニセックス', 'カジュアル'],
    prRequired: true,
    requiredHashtags: ['#PR', '#BEAMSBOY'],
  },
  {
    id: 'f-008',
    brandName: 'VA Vendome Aoyama',
    productName: 'K10 ピンクサファイア リング',
    category: 'fashion',
    summary: 'ジュエリーをデイリーに',
    description: '誕生石ピンクサファイア (¥35,200) を日常コーデに溶かす。',
    fee: 80000,
    feeNote: '+ リング 1 点進呈',
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-25',
    contact: { type: 'email', address: 'va-pr@vavendome.co.jp' },
    audienceTags: ['20代女性', '30代女性', 'ジュエリー', '上質'],
    prRequired: true,
    requiredHashtags: ['#PR', '#VAVendomeAoyama'],
  },
  {
    id: 'f-009',
    brandName: '4°C (ヨンドシー)',
    productName: 'ダイヤモンドネックレス',
    category: 'fashion',
    summary: 'プレゼント文脈の投稿',
    description: '誕生日・記念日プレゼントとしての提案。',
    fee: 120000,
    minFollowers: 20000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-11-05',
    contact: { type: 'email', address: 'pr@fdcp.co.jp' },
    audienceTags: ['20代女性', '30代女性', 'ジュエリー', 'ギフト'],
    prRequired: true,
    requiredHashtags: ['#PR', '#4degrees'],
    exclusive: true,
  },
  {
    id: 'f-010',
    brandName: 'agete (アガット)',
    productName: 'K10 ダイヤモンドピアス',
    category: 'fashion',
    summary: '小さなジュエリーをミニマルに',
    description: '日常の中の「ご褒美ジュエリー」訴求。',
    fee: 75000,
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-15',
    contact: { type: 'email', address: 'agete-pr@iac.co.jp' },
    audienceTags: ['20代女性', '30代女性', 'ジュエリー'],
    prRequired: true,
    requiredHashtags: ['#PR', '#agete'],
  },
  {
    id: 'f-011',
    brandName: 'PLST (プラステ)',
    productName: 'センタープレスパンツ',
    category: 'fashion',
    summary: '美脚パンツの 3 コーデ',
    description: '通勤・休日・お出かけの 3 着回し。',
    fee: 45000,
    feeNote: '+ パンツ 1 本 (¥9,900 相当)',
    minFollowers: 7000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-25',
    contact: { type: 'email', address: 'plst-pr@uniqlo.com' },
    audienceTags: ['30代女性', '40代女性', 'OL', '通勤'],
    prRequired: true,
    requiredHashtags: ['#PR', '#PLST'],
  },
  {
    id: 'f-012',
    brandName: 'Levi\'s 日本',
    productName: '501 オリジナルフィット',
    category: 'fashion',
    summary: 'デニムを着回す春夏コーデ',
    description: '同じ 1 本のデニムで 4 コーデ。',
    fee: 95000,
    feeNote: '+ デニム 1 本 (¥17,600 相当)',
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-15',
    contact: { type: 'email', address: 'jp-creator@levi.com' },
    audienceTags: ['20代', '30代', 'カジュアル', 'デニム'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Levis'],
  },
  {
    id: 'f-013',
    brandName: 'WEGO',
    productName: 'Y2K ファッションコレクション',
    category: 'fashion',
    summary: 'Y2K トレンドの GRWM',
    description: 'TikTok の Get Ready With Me 形式。',
    fee: 25000,
    minFollowers: 3000,
    platform: 'tiktok',
    contentType: 'short',
    deadline: '2026-07-30',
    contact: { type: 'email', address: 'wego-pr@wego.co.jp' },
    audienceTags: ['10代', 'Y2K', 'トレンド', '学生'],
    prRequired: true,
    requiredHashtags: ['#PR', '#WEGO'],
  },
  {
    id: 'f-014',
    brandName: 'STUDIOUS',
    productName: 'リネンセットアップ',
    category: 'fashion',
    summary: '大人カジュアルのセットアップ',
    description: 'オン・オフ着回せるセットアップ。',
    fee: 60000,
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-15',
    contact: { type: 'email', address: 'pr@studious.co.jp' },
    audienceTags: ['20代女性', '30代女性', 'ナチュラル', '大人カジュアル'],
    prRequired: true,
    requiredHashtags: ['#PR', '#STUDIOUS'],
  },
  {
    id: 'f-015',
    brandName: 'ABC-MART',
    productName: 'New Balance 574 — 2026 SS 限定カラー',
    category: 'fashion',
    summary: 'スニーカーコーデ 3 投稿',
    description: 'スニーカー 1 足で 3 着回しコーデ。',
    fee: 50000,
    feeNote: '+ スニーカー 1 足 (¥13,200 相当)',
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-30',
    contact: { type: 'email', address: 'abc-mart-pr@abc-mart.co.jp' },
    audienceTags: ['20代', '30代', 'スニーカー', 'ストリート'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ABCMART'],
  },
  {
    id: 'f-016',
    brandName: 'AOKI',
    productName: 'クールビズ ノーアイロン シャツ',
    category: 'fashion',
    summary: 'ビジネスマン向け夏シャツ',
    description: '通勤シーンを 60 秒リールで。',
    fee: 38000,
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-06-30',
    contact: { type: 'email', address: 'aoki-pr@aoki-style.com' },
    audienceTags: ['30代男性', '40代男性', 'ビジネス'],
    prRequired: true,
    requiredHashtags: ['#PR', '#AOKI'],
  },

  // ─── ヘルス / フィットネス (12) ───────────────────────────
  {
    id: 'h-001',
    brandName: 'マイプロテイン (Myprotein) 日本',
    productName: 'Impact ホエイプロテイン — ミルクティー味',
    category: 'health',
    summary: 'トレーニング後のシェイク動画',
    description: 'シェイカーに入れて振る瞬間 → グラスに注いで色を見せる構図。',
    fee: 35000,
    feeNote: '+ 2.5kg 1 袋進呈',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-25',
    contact: { type: 'email', address: 'jp-affiliate@myprotein.com' },
    audienceTags: ['20代', '30代', 'フィットネス', '筋トレ'],
    prRequired: true,
    requiredHashtags: ['#PR', '#マイプロテイン'],
  },
  {
    id: 'h-002',
    brandName: 'DHC',
    productName: 'マルチビタミン サプリメント',
    category: 'health',
    summary: 'デイリーサプリ習慣',
    description: '朝食後のサプリ習慣を 1 分動画で。',
    fee: 25000,
    minFollowers: 4000,
    platform: 'tiktok',
    contentType: 'short',
    deadline: '2026-07-15',
    contact: { type: 'email', address: 'dhc-pr@dhc.co.jp' },
    audienceTags: ['30代', '40代', 'ヘルスケア', '主婦'],
    prRequired: true,
    requiredHashtags: ['#PR', '#DHCサプリ'],
  },
  {
    id: 'h-003',
    brandName: 'FANCL (ファンケル)',
    productName: 'カロリミット',
    category: 'health',
    summary: '会食前のお守りサプリ',
    description: '外食シーンと絡めた 2 投稿。',
    fee: 42000,
    feeNote: '+ 30 回分 (¥1,800 相当)',
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-15',
    contact: { type: 'email', address: 'fancl-pr@fancl.co.jp' },
    audienceTags: ['30代女性', '40代女性', 'ダイエット'],
    prRequired: true,
    requiredHashtags: ['#PR', '#カロリミット'],
  },
  {
    id: 'h-004',
    brandName: 'chocoZAP',
    productName: 'コンビニジム月額 ¥3,278 — 体験会',
    category: 'health',
    summary: '近所のジム体験レポ',
    description: '実際に近所の店舗を 2 週間体験 → 朝活の 1 投稿。',
    fee: 55000,
    feeNote: '+ 3 ヶ月分無料 (¥9,834 相当)',
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-30',
    contact: { type: 'form', url: 'https://chocozap.jp/creator-program' },
    audienceTags: ['20代', '30代', 'フィットネス初心者', '時短'],
    prRequired: true,
    requiredHashtags: ['#PR', '#chocoZAP'],
  },
  {
    id: 'h-005',
    brandName: 'Anytime Fitness 日本',
    productName: '24 時間ジム — 月額会員',
    category: 'health',
    summary: '本格派ジムの夜活レポ',
    description: '23 時の閑散時間にトレ → 翌朝の達成感。',
    fee: 75000,
    feeNote: '+ 1 ヶ月体験 (¥8,800 相当)',
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-10',
    contact: { type: 'email', address: 'anytime-jp@anytimefitness.co.jp' },
    audienceTags: ['20代', '30代', '筋トレ', '夜型'],
    prRequired: true,
    requiredHashtags: ['#PR', '#エニタイムフィットネス'],
  },
  {
    id: 'h-006',
    brandName: 'クラチャイダムゴールド (REDIB)',
    productName: '黒生姜サプリ — 30 日分',
    category: 'health',
    summary: '40 代男性向け活力サプリ',
    description: 'パパ・ビジネスマン層に向けた誠実なレビュー。',
    fee: 50000,
    minFollowers: 5000,
    platform: 'youtube',
    contentType: 'longform',
    deadline: '2026-08-31',
    contact: { type: 'email', address: 'pr@redib.co.jp' },
    audienceTags: ['40代男性', '50代男性', 'ヘルスケア'],
    prRequired: true,
    requiredHashtags: ['#PR', '#クラチャイダム'],
  },
  {
    id: 'h-007',
    brandName: 'ピラティスK',
    productName: 'マシンピラティス — 初回体験',
    category: 'health',
    summary: 'ピラティス体験レポ',
    description: '実店舗での 50 分体験を 60 秒リールに。',
    fee: 40000,
    feeNote: '+ 体験回数券 4 回 (¥9,840 相当)',
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-20',
    contact: { type: 'email', address: 'pilates-k-pr@k-co.jp' },
    audienceTags: ['20代女性', '30代女性', 'ピラティス', 'ボディメイク'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ピラティスK'],
  },
  {
    id: 'h-008',
    brandName: 'LAVA (ホットヨガ)',
    productName: '体験キャンペーン — ¥0',
    category: 'health',
    summary: 'ヨガ初心者向けレポ',
    description: '体験 → 1 週間後の変化を 2 投稿。',
    fee: 30000,
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-07-30',
    contact: { type: 'email', address: 'lava-pr@lava-international.co.jp' },
    audienceTags: ['20代女性', '30代女性', 'ヨガ初心者'],
    prRequired: true,
    requiredHashtags: ['#PR', '#LAVA'],
  },
  {
    id: 'h-009',
    brandName: 'BASE BREAD',
    productName: '完全栄養食パン — ミニ食パン プレーン',
    category: 'health',
    summary: '時短朝食レポ',
    description: '忙しい朝の朝食シーンを 30 秒リール。',
    fee: 32000,
    feeNote: '+ 1 ヶ月分セット (¥3,500 相当)',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-10',
    contact: { type: 'email', address: 'partner@basefood.co.jp' },
    audienceTags: ['20代', '30代', '時短', 'ビジネス'],
    prRequired: true,
    requiredHashtags: ['#PR', '#BASEBREAD'],
  },
  {
    id: 'h-010',
    brandName: 'POLA グランラグゼ',
    productName: 'インナーロック リキッドII',
    category: 'health',
    summary: 'インナーケア美容ドリンク',
    description: '1 ヶ月飲み続けたレポ。グラスに注ぐ撮影。',
    fee: 110000,
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-20',
    contact: { type: 'email', address: 'pola-pr@pola.co.jp' },
    audienceTags: ['30代女性', '40代女性', 'インナーケア', '美容'],
    prRequired: true,
    requiredHashtags: ['#PR', '#POLA'],
  },
  {
    id: 'h-011',
    brandName: 'Apple Watch (Apple Japan)',
    productName: 'Apple Watch Series 11 — フィットネス活用',
    category: 'health',
    summary: 'ワークアウト計測の 1 週間レポ',
    description: 'ランニング・睡眠・心拍を 1 週間ログ。',
    fee: 150000,
    feeNote: '+ Apple Watch 1 台貸与 (返却制)',
    minFollowers: 25000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'apple-jp-influencer@apple.com' },
    audienceTags: ['20代', '30代', 'テック', 'フィットネス'],
    prRequired: true,
    requiredHashtags: ['#PR', '#AppleWatch'],
    exclusive: true,
  },
  {
    id: 'h-012',
    brandName: 'カーブス (Curves) 日本',
    productName: '30 分フィットネス — 50+ 女性向け',
    category: 'health',
    summary: '50 代女性向けジムレポ',
    description: 'お母さん世代向けに 1 週間レポ。',
    fee: 45000,
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-15',
    contact: { type: 'email', address: 'curves-pr@curves.co.jp' },
    audienceTags: ['40代女性', '50代女性', 'シニアフィットネス'],
    prRequired: true,
    requiredHashtags: ['#PR', '#カーブス'],
  },

  // ─── 食品 / グルメ (15) ─────────────────────────────────
  {
    id: 'g-001',
    brandName: 'Oisix',
    productName: 'ミールキット Kit Oisix 5 食セット',
    category: 'food',
    summary: '時短料理リール',
    description: '20 分で完成する晩ごはんを 60 秒リールで。',
    fee: 40000,
    feeNote: '+ Kit Oisix 5 食 (¥6,000 相当)',
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-25',
    contact: { type: 'email', address: 'partner@oisix.com' },
    audienceTags: ['30代女性', '40代女性', '主婦', '時短料理'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Oisix'],
  },
  {
    id: 'g-002',
    brandName: 'nosh (ナッシュ)',
    productName: '冷凍宅配 60 メニュー — 6 食セット',
    category: 'food',
    summary: '宅配冷凍食レポ',
    description: '一人暮らしの食事に組み込む 1 週間レポ。',
    fee: 50000,
    feeNote: '+ 2 週間分 (¥7,800 相当)',
    minFollowers: 7000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-30',
    contact: { type: 'email', address: 'partner@nosh.jp' },
    audienceTags: ['20代', '30代', '一人暮らし', '時短'],
    prRequired: true,
    requiredHashtags: ['#PR', '#nosh'],
  },
  {
    id: 'g-003',
    brandName: 'スターバックス コーヒー ジャパン',
    productName: '夏の新作フラペチーノ',
    category: 'food',
    summary: '新作レビューストーリー',
    description: '発売日に飲んだ感想を 5 ストーリー連投。',
    fee: 60000,
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'story',
    deadline: '2026-06-20',
    contact: { type: 'email', address: 'starbucks-pr@sbux.jp' },
    audienceTags: ['10代', '20代女性', 'カフェ', 'スイーツ'],
    prRequired: true,
    requiredHashtags: ['#PR', '#スタバ新作'],
  },
  {
    id: 'g-004',
    brandName: 'タリーズコーヒー',
    productName: 'バリスタ スペシャル — ロイヤルミルクティー',
    category: 'food',
    summary: 'カフェ滞在レビュー',
    description: '店内で過ごす朝の 1 時間を 4 枚フィードに。',
    fee: 35000,
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-07-15',
    contact: { type: 'email', address: 'tullys-pr@tullys.co.jp' },
    audienceTags: ['20代', '30代', 'カフェ巡り'],
    prRequired: true,
    requiredHashtags: ['#PR', '#タリーズ'],
  },
  {
    id: 'g-005',
    brandName: '日比谷花壇',
    productName: '父の日 アレンジメントギフト',
    category: 'food',
    summary: 'ギフトアンボックス',
    description: '届いた箱を開ける瞬間 → 飾る場所までを 1 投稿。',
    fee: 45000,
    feeNote: '+ アレンジメント 1 点 (¥6,600 相当)',
    minFollowers: 7000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-06-15',
    contact: { type: 'email', address: 'hibiya-pr@hibiya-kadan.co.jp' },
    audienceTags: ['30代', '40代', 'ギフト', '家族'],
    prRequired: true,
    requiredHashtags: ['#PR', '#日比谷花壇'],
  },
  {
    id: 'g-006',
    brandName: '叶 匠寿庵 (滋賀)',
    productName: '夏限定 水羊羹詰め合わせ',
    category: 'food',
    summary: '老舗和菓子のテーブルフォト',
    description: '湯のみと一緒に静かなテーブルフォトで。',
    fee: 32000,
    feeNote: '+ 詰め合わせ 1 箱 (¥3,240 相当)',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-07-20',
    contact: { type: 'email', address: 'pr@kanou-shoujuan.co.jp' },
    audienceTags: ['30代', '40代', '和菓子', 'お取り寄せ'],
    prRequired: true,
    requiredHashtags: ['#PR', '#叶匠寿庵'],
  },
  {
    id: 'g-007',
    brandName: 'COEDO ビール (協同商事)',
    productName: 'COEDO 瑠璃 — ピルスナー',
    category: 'food',
    summary: 'クラフトビール晩酌',
    description: '夏の夕方の晩酌写真。グラスへの注ぎ方ガイド付き。',
    fee: 38000,
    feeNote: '+ 4 種飲み比べセット (¥3,200 相当)',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-10',
    contact: { type: 'email', address: 'pr@coedobrewery.com' },
    audienceTags: ['30代', '40代', 'お酒', 'クラフトビール'],
    prRequired: true,
    requiredHashtags: ['#PR', '#COEDOビール'],
  },
  {
    id: 'g-008',
    brandName: 'グルテンフリー専門店 grano',
    productName: '米粉パン定期便',
    category: 'food',
    summary: 'グルテンフリー朝食',
    description: '小麦不使用の朝食シーンを 30 秒で。',
    fee: 25000,
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-25',
    contact: { type: 'email', address: 'grano-pr@grano-bread.jp' },
    audienceTags: ['20代女性', '30代女性', 'グルテンフリー', '健康'],
    prRequired: true,
    requiredHashtags: ['#PR', '#granoグルテンフリー'],
  },
  {
    id: 'g-009',
    brandName: 'ROYCE\' (ロイズ)',
    productName: '生チョコレート — オーレ',
    category: 'food',
    summary: '北海道スイーツ アンボックス',
    description: '冷蔵便で届く瞬間と、冷たい状態の口どけ。',
    fee: 30000,
    feeNote: '+ 生チョコ詰め合わせ (¥3,000 相当)',
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-15',
    contact: { type: 'email', address: 'pr@royce.com' },
    audienceTags: ['20代女性', '30代女性', 'スイーツ', 'お取り寄せ'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ロイズ'],
  },
  {
    id: 'g-010',
    brandName: 'Minimal — Bean to Bar Chocolate',
    productName: 'チョコレート ストロベリー (季節限定)',
    category: 'food',
    summary: 'クラフトチョコのフィード',
    description: 'パッケージのデザインと中身を 1 投稿で。',
    fee: 42000,
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-30',
    contact: { type: 'email', address: 'partner@mini-mal.tokyo' },
    audienceTags: ['20代', '30代', 'チョコレート', 'クラフト'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Minimalチョコ'],
  },
  {
    id: 'g-011',
    brandName: '無印良品 食品',
    productName: '不揃いバウム — ココナッツ',
    category: 'food',
    summary: 'コスパスイーツ',
    description: 'おやつタイムのテーブルフォト。',
    fee: 35000,
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-20',
    contact: { type: 'email', address: 'muji-creator@ryohin-keikaku.jp' },
    audienceTags: ['20代', '30代', '無印良品', 'シンプル'],
    prRequired: true,
    requiredHashtags: ['#PR', '#無印良品'],
  },
  {
    id: 'g-012',
    brandName: 'カルディコーヒーファーム',
    productName: 'もへじ 春の桜あんバウム',
    category: 'food',
    summary: '輸入食品店の発掘レポ',
    description: '店内で見つけた商品 5 つを 60 秒紹介。',
    fee: 28000,
    minFollowers: 4000,
    platform: 'tiktok',
    contentType: 'short',
    deadline: '2026-07-20',
    contact: { type: 'email', address: 'kaldi-pr@kaldi.co.jp' },
    audienceTags: ['20代', '30代', 'スイーツ', '輸入食品'],
    prRequired: true,
    requiredHashtags: ['#PR', '#カルディ'],
  },
  {
    id: 'g-013',
    brandName: 'GREEN SPOON',
    productName: 'スムージー 8 食セット',
    category: 'food',
    summary: '朝のスムージーレポ',
    description: '冷凍 → ブレンダーへ。色と栄養を見せる構図。',
    fee: 38000,
    feeNote: '+ 8 食セット (¥6,560 相当)',
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-30',
    contact: { type: 'email', address: 'partner@greenspoon.jp' },
    audienceTags: ['20代女性', '30代女性', '朝活', 'ヘルシー'],
    prRequired: true,
    requiredHashtags: ['#PR', '#GREENSPOON'],
  },
  {
    id: 'g-014',
    brandName: 'TASTE TABLE',
    productName: 'シェフ監修ミールキット',
    category: 'food',
    summary: 'おうちで本格料理',
    description: 'シェフのレシピを再現する 60 秒動画。',
    fee: 45000,
    minFollowers: 7000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-10',
    contact: { type: 'email', address: 'pr@tastetable.jp' },
    audienceTags: ['30代女性', '40代女性', '料理好き'],
    prRequired: true,
    requiredHashtags: ['#PR', '#TASTETABLE'],
  },
  {
    id: 'g-015',
    brandName: 'ピザーラ (Pizza-La)',
    productName: 'クワトロ・ジャパン デリバリー',
    category: 'food',
    summary: 'ホームパーティーレポ',
    description: '友人と集まる金曜夜のリビング。',
    fee: 32000,
    feeNote: '+ デリバリークーポン ¥5,000',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-25',
    contact: { type: 'email', address: 'pizzala-pr@four-seeds.co.jp' },
    audienceTags: ['20代', '30代', 'ホームパーティー'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ピザーラ'],
  },

  // ─── ライフスタイル (12) ────────────────────────────────
  {
    id: 'l-001',
    brandName: '無印良品 (生活雑貨)',
    productName: 'パイン材ユニットシェルフ',
    category: 'lifestyle',
    summary: '部屋づくりの 3 投稿',
    description: '組み立て → 配置 → 完成までの 3 ステップ。',
    fee: 80000,
    feeNote: '+ シェルフ 1 セット (¥15,900 相当)',
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'muji-living@ryohin-keikaku.jp' },
    audienceTags: ['30代', 'インテリア', '一人暮らし'],
    prRequired: true,
    requiredHashtags: ['#PR', '#無印良品の家具'],
  },
  {
    id: 'l-002',
    brandName: 'ニトリ',
    productName: 'N クール 接触冷感 寝具シリーズ',
    category: 'lifestyle',
    summary: '夏の寝具レポ',
    description: '夏の夜の寝室シーンを 30 秒で。',
    fee: 50000,
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-10',
    contact: { type: 'email', address: 'nitori-creator@nitori.co.jp' },
    audienceTags: ['30代', '40代', '主婦', '家族'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ニトリ'],
  },
  {
    id: 'l-003',
    brandName: 'Francfranc',
    productName: 'フレフレ ハンディファン',
    category: 'lifestyle',
    summary: '夏の通勤アイテム',
    description: '駅で・カフェで・公園で。3 シーンの 60 秒リール。',
    fee: 30000,
    feeNote: '+ ハンディファン 1 台 (¥3,300 相当)',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-06-25',
    contact: { type: 'email', address: 'francfranc-pr@francfranc.com' },
    audienceTags: ['20代女性', '30代女性', '夏', 'ガジェット'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Francfranc'],
  },
  {
    id: 'l-004',
    brandName: 'Snow Peak',
    productName: 'タクード 焚火台',
    category: 'lifestyle',
    summary: 'キャンプギアの夜',
    description: '焚火を 30 秒で美しく撮る。',
    fee: 90000,
    feeNote: '+ 焚火台 1 台 (¥30,800 相当)',
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'pr@snowpeak.co.jp' },
    audienceTags: ['30代', '40代', 'キャンプ', 'アウトドア'],
    prRequired: true,
    requiredHashtags: ['#PR', '#snowpeak'],
    exclusive: true,
  },
  {
    id: 'l-005',
    brandName: 'IKEA 日本',
    productName: 'BILLY 本棚 — 2026 リニューアル',
    category: 'lifestyle',
    summary: 'お部屋ビフォーアフター',
    description: '本棚の前後を比較。組み立てプロセスも 30 秒で。',
    fee: 70000,
    feeNote: '+ 本棚 1 台 (¥14,990 相当)',
    minFollowers: 10000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-10-25',
    contact: { type: 'email', address: 'ikea-jp-creators@ikea.co.jp' },
    audienceTags: ['20代', '30代', 'インテリア', '北欧'],
    prRequired: true,
    requiredHashtags: ['#PR', '#IKEA'],
  },
  {
    id: 'l-006',
    brandName: 'Aesop (アーポップ) ホーム',
    productName: 'ポストポー アロマティック ルームスプレー',
    category: 'lifestyle',
    summary: 'おうち香りシーン',
    description: '玄関でひと吹き。ボトルの撮り方ガイド付き。',
    fee: 65000,
    minFollowers: 10000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-30',
    contact: { type: 'email', address: 'jp.home@aesop.com' },
    audienceTags: ['30代', '40代', 'インテリア', '上質'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Aesop'],
  },
  {
    id: 'l-007',
    brandName: 'LOFT',
    productName: '文房具フェア 2026 夏',
    category: 'lifestyle',
    summary: '文具好きの戦利品',
    description: 'お買い物リール 60 秒。',
    fee: 35000,
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-20',
    contact: { type: 'email', address: 'loft-pr@loft.co.jp' },
    audienceTags: ['20代', '30代', '文具好き', 'クリエイティブ'],
    prRequired: true,
    requiredHashtags: ['#PR', '#LOFT'],
  },
  {
    id: 'l-008',
    brandName: 'スリーコインズ (3COINS)',
    productName: '夏のキッチン雑貨',
    category: 'lifestyle',
    summary: '¥300 アイテムでキッチン整理',
    description: '購入品開封 → 設置の 60 秒リール。',
    fee: 25000,
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-15',
    contact: { type: 'email', address: '3coins-pr@palgroup.co.jp' },
    audienceTags: ['20代女性', '30代女性', 'プチプラ', '主婦'],
    prRequired: true,
    requiredHashtags: ['#PR', '#3COINS'],
  },
  {
    id: 'l-009',
    brandName: 'カインズ (CAINZ)',
    productName: 'Kumimoku DIY ペイント',
    category: 'lifestyle',
    summary: 'おうち DIY ビフォーアフター',
    description: '家具をペイントする 1 日。',
    fee: 40000,
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-25',
    contact: { type: 'email', address: 'cainz-creator@cainz.co.jp' },
    audienceTags: ['30代', '40代', 'DIY', 'インテリア'],
    prRequired: true,
    requiredHashtags: ['#PR', '#カインズ'],
  },
  {
    id: 'l-010',
    brandName: 'KEYUCA (ケユカ)',
    productName: 'シリコーン キッチンウェア',
    category: 'lifestyle',
    summary: 'モノトーンキッチン',
    description: 'シンプルキッチンの 3 枚フィード。',
    fee: 32000,
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-30',
    contact: { type: 'email', address: 'keyuca-pr@keyuca.com' },
    audienceTags: ['30代女性', '40代女性', 'インテリア', 'シンプル'],
    prRequired: true,
    requiredHashtags: ['#PR', '#KEYUCA'],
  },
  {
    id: 'l-011',
    brandName: 'BALMUDA (バルミューダ)',
    productName: 'The Toaster',
    category: 'lifestyle',
    summary: '朝のトースト動画',
    description: 'パンが膨らむ瞬間を 30 秒リール。',
    fee: 95000,
    feeNote: '+ トースター 1 台 (¥30,580 相当)',
    minFollowers: 18000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-10-15',
    contact: { type: 'email', address: 'balmuda-pr@balmuda.com' },
    audienceTags: ['30代', '40代', 'インテリア', '家電'],
    prRequired: true,
    requiredHashtags: ['#PR', '#BALMUDA'],
    exclusive: true,
  },
  {
    id: 'l-012',
    brandName: 'Dyson 日本',
    productName: 'V15 Detect コードレス掃除機',
    category: 'lifestyle',
    summary: '床掃除の科学',
    description: 'レーザー検出機能を 60 秒で見せる。',
    fee: 200000,
    feeNote: '+ 掃除機 1 台 (¥99,000 相当・返却制)',
    minFollowers: 30000,
    platform: 'youtube',
    contentType: 'longform',
    deadline: '2026-10-30',
    contact: { type: 'email', address: 'dyson-jp-creator@dyson.com' },
    audienceTags: ['30代', '40代', '家電', '家事'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Dyson'],
    exclusive: true,
  },

  // ─── 旅行 / 体験 (8) ───────────────────────────────────
  {
    id: 't-001',
    brandName: 'HafH (ハフ)',
    productName: '多拠点生活サブスク — 月額プラン',
    category: 'travel',
    summary: '1 週間の地方滞在レポ',
    description: '実際に 1 都市に 1 週間滞在 → ワーケーション動画。',
    fee: 100000,
    feeNote: '+ 1 ヶ月分宿泊権 (¥30,800 相当)',
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'partner@hafh.com' },
    audienceTags: ['20代', '30代', 'ワーケーション', 'デジタルノマド'],
    prRequired: true,
    requiredHashtags: ['#PR', '#HafH'],
  },
  {
    id: 't-002',
    brandName: 'OYO Life 日本',
    productName: '東京・大阪 マンスリーマンション',
    category: 'travel',
    summary: '東京 1 ヶ月滞在レポ',
    description: '実滞在を 4 投稿でストーリーテリング。',
    fee: 80000,
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-15',
    contact: { type: 'email', address: 'oyolife-jp@oyorooms.com' },
    audienceTags: ['20代', '30代', '転勤', '一人暮らし'],
    prRequired: true,
    requiredHashtags: ['#PR', '#OYOLife'],
  },
  {
    id: 't-003',
    brandName: 'ソウ・エクスペリエンス',
    productName: 'カタログギフト — Special Experience',
    category: 'travel',
    summary: '体験ギフトのプレゼント',
    description: '体験を選ぶ → 実体験までの 2 投稿。',
    fee: 50000,
    feeNote: '+ カタログ 1 冊 (¥11,000 相当)',
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-11-10',
    contact: { type: 'email', address: 'sowxp-pr@sowxp.co.jp' },
    audienceTags: ['30代', 'ギフト', '体験'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ソウエクスペリエンス'],
  },
  {
    id: 't-004',
    brandName: '星野リゾート',
    productName: '界 仙石原 — 滞在企画',
    category: 'travel',
    summary: '温泉旅行 2 泊レポ',
    description: '宿泊体験を 60 秒リールで。',
    fee: 250000,
    feeNote: '+ 2 泊宿泊 (¥80,000 相当・2 名)',
    minFollowers: 50000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-11-20',
    contact: { type: 'email', address: 'kai-pr@hoshinoresort.com' },
    audienceTags: ['30代女性', '40代女性', '温泉', '上質'],
    prRequired: true,
    requiredHashtags: ['#PR', '#界仙石原'],
    exclusive: true,
  },
  {
    id: 't-005',
    brandName: 'KKday Japan',
    productName: '京都人気体験チケット — 着物レンタル',
    category: 'travel',
    summary: '京都散策レポ',
    description: '着物姿の 1 日を 5 ストーリー。',
    fee: 45000,
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'story',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'kkday-jp@kkday.com' },
    audienceTags: ['20代女性', '30代女性', '京都', '旅行'],
    prRequired: true,
    requiredHashtags: ['#PR', '#KKday'],
  },
  {
    id: 't-006',
    brandName: 'JR 東日本 びゅう',
    productName: '東北「えきねっと」割引きっぷ',
    category: 'travel',
    summary: '日帰り旅行レポ',
    description: '東北 1 都市の日帰りを 60 秒リール。',
    fee: 55000,
    feeNote: '+ きっぷ代 (¥15,000 相当)',
    minFollowers: 10000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-31',
    contact: { type: 'form', url: 'https://www.eki-net.com/creator-program' },
    audienceTags: ['20代', '30代', '旅行', '東北'],
    prRequired: true,
    requiredHashtags: ['#PR', '#えきねっと'],
  },
  {
    id: 't-007',
    brandName: 'Airbnb Japan',
    productName: '一棟貸し体験 — 京都町家',
    category: 'travel',
    summary: '町家ステイレポ',
    description: '友人と滞在する 1 泊 2 日を 4 投稿に。',
    fee: 120000,
    minFollowers: 20000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-10-30',
    contact: { type: 'email', address: 'airbnb-jp-creators@airbnb.com' },
    audienceTags: ['20代', '30代', '旅行', '京都', 'グループ旅'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Airbnb'],
  },
  {
    id: 't-008',
    brandName: 'JTB',
    productName: '近場リゾート 夏休みプラン',
    category: 'travel',
    summary: '家族旅行レポ',
    description: '家族で行く近場リゾート 2 泊 3 日。',
    fee: 90000,
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-07-25',
    contact: { type: 'email', address: 'jtb-creator@jtb.co.jp' },
    audienceTags: ['30代', '40代', '家族', '旅行'],
    prRequired: true,
    requiredHashtags: ['#PR', '#JTB'],
  },

  // ─── ペット (5) ────────────────────────────────────────
  {
    id: 'p-001',
    brandName: 'PETOKOTO FOODS',
    productName: 'パーソナライズ犬ごはん',
    category: 'pet',
    summary: '愛犬の食事レポ',
    description: '愛犬が食べる瞬間を 30 秒で。',
    fee: 35000,
    feeNote: '+ 2 週間分 (¥6,000 相当)',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-25',
    contact: { type: 'email', address: 'partner@petokoto.com' },
    audienceTags: ['犬好き', '20代', '30代', 'ペット'],
    prRequired: true,
    requiredHashtags: ['#PR', '#PETOKOTO'],
  },
  {
    id: 'p-002',
    brandName: 'PEPPY (ペピイ)',
    productName: '猫用キャットタワー — 木目調',
    category: 'pet',
    summary: 'キャットタワー組み立てレポ',
    description: '組み立て → 愛猫が登る瞬間まで。',
    fee: 30000,
    feeNote: '+ キャットタワー 1 台 (¥19,800 相当)',
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-15',
    contact: { type: 'email', address: 'peppy-pr@peppynet.com' },
    audienceTags: ['猫好き', '20代女性', '30代女性'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ペピイ'],
  },
  {
    id: 'p-003',
    brandName: 'Mister Donut',
    productName: 'ポン・デ・ライオン グッズ',
    category: 'pet',
    summary: 'ペットと一緒のキャラクターコラボ',
    description: '愛犬と一緒に写った 4 枚フィード。',
    fee: 28000,
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-08-15',
    contact: { type: 'email', address: 'misdo-pr@misterdonut.jp' },
    audienceTags: ['ペット', '20代', '30代'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ミスドポンデ'],
  },
  {
    id: 'p-004',
    brandName: 'PETPET (ペットペット)',
    productName: '猫トイレ砂 — 紙系',
    category: 'pet',
    summary: '猫飼いの毎日',
    description: 'トイレ周りの片付けレポ。',
    fee: 22000,
    minFollowers: 3500,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-10',
    contact: { type: 'email', address: 'petpet-pr@unicharm.co.jp' },
    audienceTags: ['猫好き', '20代', '30代', '主婦'],
    prRequired: true,
    requiredHashtags: ['#PR', '#PETPET'],
  },
  {
    id: 'p-005',
    brandName: 'GREEN DOG',
    productName: 'プレミアム犬ごはんサンプリング',
    category: 'pet',
    summary: 'ドッグフード食いつきレポ',
    description: '愛犬が食べる瞬間を 30 秒リール。',
    fee: 25000,
    minFollowers: 4000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-20',
    contact: { type: 'email', address: 'greendog-pr@greendog.jp' },
    audienceTags: ['犬好き', '30代', '40代'],
    prRequired: true,
    requiredHashtags: ['#PR', '#GREENDOG'],
  },

  // ─── テック / ガジェット (8) ────────────────────────────
  {
    id: 'tc-001',
    brandName: 'Anker Japan',
    productName: 'PowerCore 10000 PD Redux',
    category: 'tech',
    summary: 'モバイルバッテリーの日常',
    description: '出張シーンを 60 秒で。',
    fee: 45000,
    feeNote: '+ バッテリー 1 台 (¥4,990 相当)',
    minFollowers: 8000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-07-30',
    contact: { type: 'email', address: 'anker-jp-creator@anker.com' },
    audienceTags: ['20代', '30代', 'テック', 'ビジネス'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Anker'],
  },
  {
    id: 'tc-002',
    brandName: 'Sony Japan',
    productName: 'WH-1000XM6 ヘッドホン',
    category: 'tech',
    summary: '通勤ヘッドホン体験',
    description: 'ノイキャンの効きを 30 秒で。',
    fee: 130000,
    feeNote: '+ ヘッドホン 1 台 (¥59,400 相当)',
    minFollowers: 25000,
    platform: 'youtube',
    contentType: 'longform',
    deadline: '2026-10-31',
    contact: { type: 'email', address: 'sony-jp-creator@sony.com' },
    audienceTags: ['20代', '30代', 'テック', 'オーディオ'],
    prRequired: true,
    requiredHashtags: ['#PR', '#SonyHeadphones'],
    exclusive: true,
  },
  {
    id: 'tc-003',
    brandName: 'iRobot Japan',
    productName: 'ルンバ コンボ j7+',
    category: 'tech',
    summary: 'ロボット掃除機の朝',
    description: 'お出かけ前にルンバを起動するシーン。',
    fee: 90000,
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-10-20',
    contact: { type: 'email', address: 'irobot-jp-pr@irobot.com' },
    audienceTags: ['30代', '40代', '主婦', '時短'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ルンバ'],
  },
  {
    id: 'tc-004',
    brandName: 'Pixel (Google Japan)',
    productName: 'Pixel 11 — マジック消しゴム',
    category: 'tech',
    summary: 'スマホカメラ機能レビュー',
    description: '写真加工の使い方を 60 秒で。',
    fee: 120000,
    feeNote: '+ Pixel 11 1 台貸与',
    minFollowers: 20000,
    platform: 'youtube',
    contentType: 'longform',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'pixel-jp-creator@google.com' },
    audienceTags: ['20代', '30代', 'テック', '写真'],
    prRequired: true,
    requiredHashtags: ['#PR', '#GooglePixel'],
  },
  {
    id: 'tc-005',
    brandName: 'BOSE 日本',
    productName: 'QuietComfort Earbuds',
    category: 'tech',
    summary: 'カフェで使うイヤホン',
    description: 'カフェでの集中作業 60 秒リール。',
    fee: 85000,
    minFollowers: 15000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-30',
    contact: { type: 'email', address: 'bose-jp-pr@bose.com' },
    audienceTags: ['20代', '30代', 'オーディオ', 'カフェ'],
    prRequired: true,
    requiredHashtags: ['#PR', '#BOSE'],
  },
  {
    id: 'tc-006',
    brandName: 'GoPro Japan',
    productName: 'HERO 13 Black',
    category: 'tech',
    summary: 'アウトドア映像レポ',
    description: 'キャンプ / 旅行で撮った 60 秒のショートムービー。',
    fee: 110000,
    feeNote: '+ HERO 13 1 台貸与',
    minFollowers: 20000,
    platform: 'youtube',
    contentType: 'longform',
    deadline: '2026-10-15',
    contact: { type: 'email', address: 'gopro-jp@gopro.com' },
    audienceTags: ['20代', '30代', 'アウトドア', '動画'],
    prRequired: true,
    requiredHashtags: ['#PR', '#GoPro'],
  },
  {
    id: 'tc-007',
    brandName: 'Logicool (Logitech) Japan',
    productName: 'MX Master 4 マウス',
    category: 'tech',
    summary: 'デスクツアー動画',
    description: '在宅ワークデスクを 60 秒紹介。',
    fee: 55000,
    feeNote: '+ マウス 1 台 (¥17,600 相当)',
    minFollowers: 10000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-20',
    contact: { type: 'email', address: 'logicool-jp-pr@logicool.com' },
    audienceTags: ['20代', '30代', 'デスクツアー', '在宅ワーク'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Logicool'],
  },
  {
    id: 'tc-008',
    brandName: 'Nintendo (任天堂)',
    productName: 'Nintendo Switch 2 — ファミリー向けタイトル',
    category: 'tech',
    summary: 'おうちゲーム時間',
    description: '家族でゲームする 30 秒リール。',
    fee: 180000,
    minFollowers: 30000,
    platform: 'youtube',
    contentType: 'longform',
    deadline: '2026-12-15',
    contact: { type: 'email', address: 'nintendo-jp-creator@nintendo.co.jp' },
    audienceTags: ['ファミリー', '20代', '30代', 'ゲーム'],
    prRequired: true,
    requiredHashtags: ['#PR', '#NintendoSwitch'],
    exclusive: true,
  },

  // ─── 学び / キャリア (5) ────────────────────────────────
  {
    id: 'lr-001',
    brandName: 'Schoo (スクー)',
    productName: 'オンライン学習サブスク — プレミアム',
    category: 'learning',
    summary: '朝活学習レポ',
    description: '朝の学習ルーティン 60 秒。',
    fee: 35000,
    feeNote: '+ 3 ヶ月分無料 (¥3,300 相当)',
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-30',
    contact: { type: 'email', address: 'schoo-pr@schoo.jp' },
    audienceTags: ['20代', '30代', '社会人学習', '朝活'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Schoo'],
  },
  {
    id: 'lr-002',
    brandName: 'Progate',
    productName: 'プログラミング学習サブスク',
    category: 'learning',
    summary: 'コーディング初心者レポ',
    description: '1 週間の学習履歴を 2 投稿。',
    fee: 30000,
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-15',
    contact: { type: 'email', address: 'progate-pr@progate.com' },
    audienceTags: ['20代', '社会人', 'プログラミング初心者'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Progate'],
  },
  {
    id: 'lr-003',
    brandName: 'Duolingo Japan',
    productName: 'Super Duolingo (有料プラン)',
    category: 'learning',
    summary: '英語学習 30 日チャレンジ',
    description: '30 日継続レポ。',
    fee: 28000,
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'duolingo-jp@duolingo.com' },
    audienceTags: ['20代', '30代', '英語', '学び'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Duolingo'],
  },
  {
    id: 'lr-004',
    brandName: 'Udemy Japan (ベネッセ)',
    productName: '人気講座バンドル — Excel / Python',
    category: 'learning',
    summary: '学習レビュー動画',
    description: '60 分の動画講座のレポ。',
    fee: 40000,
    feeNote: '+ 講座 5 本 (¥10,000 相当)',
    minFollowers: 7000,
    platform: 'youtube',
    contentType: 'longform',
    deadline: '2026-10-20',
    contact: { type: 'email', address: 'udemy-jp@benesse.co.jp' },
    audienceTags: ['20代', '30代', '社会人学習'],
    prRequired: true,
    requiredHashtags: ['#PR', '#Udemy'],
  },
  {
    id: 'lr-005',
    brandName: 'BIZREACH (ビズリーチ)',
    productName: 'ハイクラス転職プラットフォーム',
    category: 'learning',
    summary: 'キャリアアップ事例',
    description: '自身の転職経験談を 60 秒で。',
    fee: 80000,
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-10-30',
    contact: { type: 'email', address: 'bizreach-pr@bizreach.co.jp' },
    audienceTags: ['30代', '40代', 'キャリア', '転職'],
    prRequired: true,
    requiredHashtags: ['#PR', '#ビズリーチ'],
  },

  // ─── ホーム / インテリア (5) ────────────────────────────
  {
    id: 'hm-001',
    brandName: 'リンナイ',
    productName: 'ガス炊飯器 — 直火匠',
    category: 'home',
    summary: '炊きたてご飯の朝',
    description: '炊飯シーンの 30 秒リール。',
    fee: 60000,
    feeNote: '+ 炊飯器 1 台 (¥36,300 相当・返却制)',
    minFollowers: 10000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-09-30',
    contact: { type: 'email', address: 'rinnai-pr@rinnai.co.jp' },
    audienceTags: ['30代', '40代', '料理', '家電'],
    prRequired: true,
    requiredHashtags: ['#PR', '#リンナイ'],
  },
  {
    id: 'hm-002',
    brandName: 'KINTO',
    productName: 'OCT カラフェセット',
    category: 'home',
    summary: 'デザインキッチン雑貨',
    description: 'コーヒーを淹れる朝の 60 秒。',
    fee: 38000,
    minFollowers: 6000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-30',
    contact: { type: 'email', address: 'kinto-pr@kinto.co.jp' },
    audienceTags: ['20代', '30代', 'コーヒー', 'デザイン'],
    prRequired: true,
    requiredHashtags: ['#PR', '#KINTO'],
  },
  {
    id: 'hm-003',
    brandName: 'マルニ木工',
    productName: 'HIROSHIMA アームチェア (深澤直人)',
    category: 'home',
    summary: 'デザイン家具のリビング',
    description: 'リビングの 4 枚フィード。',
    fee: 150000,
    minFollowers: 25000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-11-30',
    contact: { type: 'email', address: 'maruni-pr@maruni.com' },
    audienceTags: ['30代', '40代', 'インテリア', 'デザイン'],
    prRequired: true,
    requiredHashtags: ['#PR', '#マルニ木工'],
    exclusive: true,
  },
  {
    id: 'hm-004',
    brandName: 'グリーンスナップ (GreenSnap)',
    productName: '観葉植物オンライン販売',
    category: 'home',
    summary: '観葉植物のあるリビング',
    description: '植物が届く → 配置の 60 秒リール。',
    fee: 28000,
    feeNote: '+ 観葉植物 1 鉢 (¥6,000 相当)',
    minFollowers: 5000,
    platform: 'instagram',
    contentType: 'reel',
    deadline: '2026-08-20',
    contact: { type: 'email', address: 'greensnap-pr@greensnap.co.jp' },
    audienceTags: ['20代', '30代', '観葉植物', 'インテリア'],
    prRequired: true,
    requiredHashtags: ['#PR', '#GreenSnap'],
  },
  {
    id: 'hm-005',
    brandName: '大塚家具',
    productName: 'ソファ 春夏フェア',
    category: 'home',
    summary: 'ショールーム訪問レポ',
    description: '実店舗体験を 4 枚フィードに。',
    fee: 70000,
    minFollowers: 12000,
    platform: 'instagram',
    contentType: 'post',
    deadline: '2026-09-25',
    contact: { type: 'email', address: 'idc-pr@idc-otsuka.jp' },
    audienceTags: ['30代', '40代', 'インテリア'],
    prRequired: true,
    requiredHashtags: ['#PR', '#大塚家具'],
  },
];

export function getAllBrandDeals(): BrandDeal[] {
  return DEALS;
}

export function getBrandDealById(id: string): BrandDeal | undefined {
  return DEALS.find(d => d.id === id);
}

export function getDealCount(): number {
  return DEALS.length;
}
