// ============================================================
// syncBusinessPlan.mjs
// ~/Desktop/CORE_事業計画_2026/*.md を src/data/businessPlan.ts に embed
// ビルド時 (prebuild) に自動実行 — 計画書をフロントから読めるようにする
// ============================================================
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const SRC_DIR = path.join(os.homedir(), 'Desktop', 'CORE_事業計画_2026');
const OUT_FILE = path.resolve(process.cwd(), 'src/data/businessPlan.ts');

function escapeForTemplate(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function extractTitle(md, fallback) {
  const m = md.match(/^#\s+(.+?)\s*$/m);
  return m ? m[1].trim() : fallback;
}

function extractLastUpdated(md) {
  // 「## 更新履歴」テーブルから最新日付を抽出
  const m = md.match(/##\s*更新履歴[\s\S]*?\|\s*(\d{4}-\d{2}-\d{2})\s*\|/);
  if (m) return m[1];
  // フォールバック: ヘッダの **作成日**: YYYY-MM-DD
  const m2 = md.match(/\*\*作成日\*\*\s*[:：]\s*(\d{4}-\d{2}-\d{2})/);
  return m2 ? m2[1] : null;
}

async function main() {
  let files = [];
  try {
    const all = await fs.readdir(SRC_DIR);
    files = all.filter(f => /^\d+_.+\.md$/i.test(f) && f.toLowerCase() !== 'readme.md').sort();
  } catch (e) {
    console.warn(`[syncBusinessPlan] ${SRC_DIR} が読めません: ${e.message}`);
  }

  const docs = [];
  for (const f of files) {
    const full = path.join(SRC_DIR, f);
    let content = '';
    try {
      content = await fs.readFile(full, 'utf8');
    } catch (e) {
      console.warn(`[syncBusinessPlan] skip ${f}: ${e.message}`);
      continue;
    }
    const slug = f.replace(/\.md$/i, '');
    const title = extractTitle(content, slug);
    const updated = extractLastUpdated(content);
    docs.push({ slug, file: f, title, updated, content });
  }

  const header = `// AUTO-GENERATED by scripts/syncBusinessPlan.mjs — DO NOT EDIT MANUALLY
// Source: ~/Desktop/CORE_事業計画_2026/*.md
// Regenerate: \`npm run sync-plan\` (or any \`npm run build\`)

export type BusinessPlanDoc = {
  slug: string;
  file: string;
  title: string;
  updated: string | null;
  content: string;
};

export const BUSINESS_PLAN_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};

export const BUSINESS_PLAN_DOCS: BusinessPlanDoc[] = [
`;

  const body = docs.map(d => {
    return `  {
    slug: ${JSON.stringify(d.slug)},
    file: ${JSON.stringify(d.file)},
    title: ${JSON.stringify(d.title)},
    updated: ${JSON.stringify(d.updated)},
    content: \`${escapeForTemplate(d.content)}\`,
  },`;
  }).join('\n');

  const footer = `\n];\n`;

  const out = header + body + footer;

  // 重要 (オーナー指示 2026-05-27):
  // Vercel ビルド時は SRC_DIR が存在しないため docs=[] になる。
  // その場合は既存ファイルを保持し、上書きしない (本番から計画書が消えるのを防ぐ)
  if (docs.length === 0) {
    try {
      const existing = await fs.readFile(OUT_FILE, 'utf8');
      // 既存ファイルに 1 件以上の slug があれば、そのまま温存
      const hasContent = /slug:\s*"/.test(existing);
      if (hasContent) {
        console.log(`[syncBusinessPlan] SRC_DIR が空/不在のため、既存の ${OUT_FILE} を温存します`);
        return;
      }
    } catch { /* 新規作成 OK */ }
  }

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, out, 'utf8');
  console.log(`[syncBusinessPlan] ${docs.length} 件の計画書を ${path.relative(process.cwd(), OUT_FILE)} に embed`);
}

main().catch(err => {
  console.error('[syncBusinessPlan] failed:', err);
  process.exit(1);
});
