// AUTO-GENERATED by scripts/syncBusinessPlan.mjs — DO NOT EDIT MANUALLY
// Source: ~/Desktop/CORE_事業計画_2026/*.md
// Regenerate: `npm run sync-plan` (or any `npm run build`)

export type BusinessPlanDoc = {
  slug: string;
  file: string;
  title: string;
  updated: string | null;
  content: string;
};

export const BUSINESS_PLAN_GENERATED_AT = "2026-05-19T00:45:12.067Z";

export const BUSINESS_PLAN_DOCS: BusinessPlanDoc[] = [

];
